/* Parfumo Fragrance Database - Austin McCummber

First - Creating three tables based on the scraped data from Parfumo. 

Tables will be: acccords (A list of all accords in the set), perfumers (Primary Key and perfumers) and
parfumodb (full table with many columns). Note that the accords table is for calculations only, and the perfumer
table has only been created for the purposes of demonstrating a simple inner join. 

Sqlizer app was used to help automate the conversion of excel files into create/insert statements. 

*/

CREATE TABLE IF NOT EXISTS parfumoaccords (
    "accord1" TEXT
);
INSERT INTO parfumoaccords VALUES ('oriental'),
	('oriental'),
	('woody'),
	('sweet'),
	('sweet'),
	('sweet'),
	('spicy'),
	('floral'),
	('floral'),
	('spicy'),
	('smoky'),
	('oriental'),
	('floral'),
	('floral'),
	('sweet'),
	('animal'),
	('spicy'),
	('sweet'),
	('citrusy'),
	('woody'),
	('sweet'),
	('green'),
	('spicy'),
	('citrusy'),
	('spicy'),
	('spicy'),
	('leathery'),
	('leathery'),
	('floral'),
	('spicy'),
	('spicy'),
	('sweet'),
	('floral'),
	('resinous'),
	('floral'),
	('floral'),
	('floral'),
	('leathery'),
	('green'),
	('woody'),
	('floral'),
	('oriental'),
	('oriental'),
	('oriental'),
	('green'),
	('oriental'),
	('woody'),
	('woody'),
	('earthy'),
	('citrusy'),
	('spicy'),
	('fresh'),
	('fresh'),
	('woody'),
	('citrusy'),
	('spicy'),
	('spicy'),
	('fresh'),
	('woody'),
	('sweet'),
	('fresh'),
	('green'),
	('fruity'),
	('sweet'),
	('chypre'),
	('chypre'),
	('sweet'),
	('oriental'),
	('floral'),
	('sweet'),
	('oriental'),
	('spicy'),
	('powdery'),
	('powdery'),
	('spicy'),
	('citrusy'),
	('citrusy'),
	('powdery'),
	('powdery'),
	('powdery'),
	('sweet'),
	('spicy'),
	('spicy'),
	('floral'),
	('woody'),
	('floral'),
	('floral'),
	('spicy'),
	('woody'),
	('chypre'),
	('chypre'),
	('floral'),
	('woody'),
	('leathery'),
	('powdery'),
	('fresh'),
	('spicy'),
	('sweet'),
	('floral'),
	('powdery'),
	('sweet'),
	('chypre'),
	('woody'),
	('woody'),
	('spicy'),
	('powdery'),
	('chypre'),
	('floral'),
	('floral'),
	('spicy'),
	('chypre'),
	('floral'),
	('oriental'),
	('gourmand'),
	('sweet'),
	('oriental'),
	('floral'),
	('citrusy'),
	('oriental'),
	('floral'),
	('powdery'),
	('sweet'),
	('sweet'),
	('floral'),
	('floral'),
	('oriental'),
	('oriental'),
	('woody'),
	('spicy'),
	('oriental'),
	('sweet'),
	('oriental'),
	('floral'),
	('spicy'),
	('oriental'),
	('chypre'),
	('woody'),
	('gourmand'),
	('sweet'),
	('sweet'),
	('sweet'),
	('spicy'),
	('spicy'),
	('leathery'),
	('woody'),
	('woody'),
	('sweet'),
	('gourmand'),
	('spicy'),
	('sweet'),
	('woody'),
	('woody'),
	('woody'),
	('sweet'),
	('sweet'),
	('sweet'),
	('sweet'),
	('sweet'),
	('chypre'),
	('spicy'),
	('spicy'),
	('oriental'),
	('spicy'),
	('sweet'),
	('sweet'),
	('sweet'),
	('spicy'),
	('sweet'),
	('oriental'),
	('sweet'),
	('fresh'),
	('fresh'),
	('woody'),
	('fresh'),
	('spicy'),
	('sweet'),
	('sweet'),
	('sweet'),
	('sweet'),
	('fresh'),
	('floral'),
	('fresh'),
	('spicy'),
	('spicy'),
	('sweet'),
	('fresh'),
	('oriental'),
	('sweet'),
	('sweet'),
	('sweet'),
	('sweet'),
	('oriental'),
	('gourmand'),
	('woody'),
	('spicy'),
	('woody'),
	('floral'),
	('fresh'),
	('sweet'),
	('spicy'),
	('fruity'),
	('spicy'),
	('spicy'),
	('green'),
	('floral'),
	('floral'),
	('sweet'),
	('sweet'),
	('sweet'),
	('sweet'),
	('woody'),
	('sweet'),
	('spicy'),
	('chypre'),
	('citrusy'),
	('spicy'),
	('powdery'),
	('powdery'),
	('sweet'),
	('powdery'),
	('powdery'),
	('animal'),
	('floral'),
	('sweet'),
	('spicy'),
	('floral'),
	('floral'),
	('oriental'),
	('floral'),
	('chypre'),
	('fresh'),
	('woody'),
	('oriental'),
	('oriental'),
	('spicy'),
	('green'),
	('citrusy'),
	('spicy'),
	('spicy'),
	('citrusy'),
	('fresh'),
	('fresh'),
	('spicy'),
	('fresh'),
	('woody'),
	('fruity'),
	('resinous'),
	('spicy'),
	('resinous'),
	('spicy');
INSERT INTO parfumoaccords VALUES ('spicy'),
	('woody'),
	('sweet'),
	('fruity'),
	('sweet'),
	('sweet'),
	('animal'),
	('sweet'),
	('sweet'),
	('sweet'),
	('fresh'),
	('floral'),
	('leathery'),
	('sweet'),
	('leathery'),
	('fruity'),
	('woody'),
	('fougere'),
	('sweet'),
	('leathery'),
	('sweet'),
	('woody'),
	('sweet'),
	('spicy'),
	('oriental'),
	('leathery'),
	('floral'),
	('fruity'),
	('woody'),
	('sweet'),
	('oriental'),
	('oriental'),
	('woody'),
	('woody'),
	('fresh'),
	('sweet'),
	('fresh'),
	('sweet'),
	('woody'),
	('woody'),
	('sweet'),
	('oriental'),
	('sweet'),
	('sweet'),
	('sweet'),
	('oriental'),
	('spicy'),
	('oriental'),
	('spicy'),
	('spicy'),
	('woody'),
	('floral'),
	('spicy'),
	('fruity'),
	('spicy'),
	('fruity'),
	('oriental'),
	('powdery'),
	('oriental'),
	('woody'),
	('spicy'),
	('spicy'),
	('powdery'),
	('sweet'),
	('floral'),
	('powdery'),
	('oriental'),
	('spicy'),
	('smoky'),
	('sweet'),
	('oriental'),
	('floral'),
	('creamy'),
	('sweet'),
	('woody'),
	('sweet'),
	('spicy'),
	('spicy'),
	('oriental'),
	('oriental'),
	('woody'),
	('powdery'),
	('green'),
	('smoky'),
	('powdery'),
	('sweet'),
	('sweet'),
	('spicy'),
	('floral'),
	('spicy'),
	('powdery'),
	('woody'),
	('spicy'),
	('spicy'),
	('floral'),
	('floral'),
	('floral'),
	('spicy'),
	('woody'),
	('fresh'),
	('woody'),
	('citrusy'),
	('sweet'),
	('fresh'),
	('fresh'),
	('green'),
	('sweet'),
	('citrusy'),
	('spicy'),
	('gourmand'),
	('citrusy'),
	('fresh'),
	('fresh'),
	('spicy'),
	('floral'),
	('floral'),
	('gourmand'),
	('sweet'),
	('sweet'),
	('floral'),
	('floral'),
	('woody'),
	('sweet'),
	('sweet'),
	('woody'),
	('fresh'),
	('woody'),
	('sweet'),
	('leathery'),
	('sweet'),
	('spicy'),
	('sweet'),
	('sweet'),
	('spicy'),
	('oriental'),
	('oriental'),
	('green'),
	('oriental'),
	('spicy'),
	('floral'),
	('floral'),
	('sweet'),
	('oriental'),
	('smoky'),
	('sweet'),
	('aquatic'),
	('woody'),
	('spicy'),
	('green'),
	('sweet'),
	('spicy'),
	('floral'),
	('oriental'),
	('spicy'),
	('woody'),
	('oriental'),
	('floral'),
	('powdery'),
	('oriental'),
	('woody'),
	('spicy'),
	('powdery'),
	('spicy'),
	('sweet'),
	('floral'),
	('spicy'),
	('spicy'),
	('powdery'),
	('powdery'),
	('powdery'),
	('floral'),
	('floral'),
	('floral'),
	('powdery'),
	('powdery'),
	('powdery'),
	('spicy'),
	('floral'),
	('green'),
	('powdery'),
	('oriental'),
	('sweet'),
	('powdery'),
	('animal'),
	('powdery'),
	('spicy'),
	('spicy'),
	('sweet'),
	('floral'),
	('gourmand'),
	('powdery'),
	('woody'),
	('woody'),
	('powdery'),
	('spicy'),
	('spicy'),
	('gourmand'),
	('spicy'),
	('woody'),
	('gourmand'),
	('earthy'),
	('earthy'),
	('spicy'),
	('spicy'),
	('spicy'),
	('fruity'),
	('floral'),
	('spicy'),
	('green'),
	('woody'),
	('sweet'),
	('sweet'),
	('oriental'),
	('gourmand'),
	('powdery'),
	('gourmand'),
	('sweet'),
	('fruity'),
	('floral'),
	('gourmand'),
	('woody'),
	('citrusy'),
	('smoky'),
	('citrusy'),
	('powdery'),
	('floral'),
	('floral'),
	('resinous'),
	('floral'),
	('woody'),
	('spicy'),
	('sweet'),
	('woody'),
	('leathery'),
	('gourmand'),
	('aquatic'),
	('spicy'),
	('oriental'),
	('oriental'),
	('gourmand'),
	('gourmand'),
	('spicy'),
	('sweet'),
	('spicy'),
	('woody'),
	('spicy'),
	('spicy'),
	('citrusy'),
	('spicy'),
	('sweet');
INSERT INTO parfumoaccords VALUES ('fresh'),
	('sweet'),
	('floral'),
	('woody'),
	('fruity'),
	('sweet'),
	('spicy'),
	('spicy'),
	('spicy'),
	('gourmand'),
	('spicy'),
	('spicy'),
	('citrusy'),
	('spicy'),
	('fruity'),
	('woody'),
	('floral'),
	('spicy'),
	('powdery'),
	('sweet'),
	('fresh'),
	('earthy'),
	('powdery'),
	('spicy'),
	('sweet'),
	('creamy'),
	('creamy'),
	('spicy'),
	('spicy'),
	('spicy'),
	('floral'),
	('smoky'),
	('woody'),
	('floral'),
	('woody'),
	('spicy'),
	('fresh'),
	('fresh'),
	('sweet'),
	('fresh'),
	('citrusy'),
	('spicy'),
	('sweet'),
	('citrusy'),
	('spicy'),
	('spicy'),
	('woody'),
	('woody'),
	('woody'),
	('oriental'),
	('oriental'),
	('spicy'),
	('spicy'),
	('sweet'),
	('fruity'),
	('fruity'),
	('spicy'),
	('floral'),
	('oriental'),
	('oriental'),
	('citrusy'),
	('spicy'),
	('spicy'),
	('spicy'),
	('smoky'),
	('sweet'),
	('spicy'),
	('green'),
	('gourmand'),
	('powdery'),
	('powdery'),
	('sweet'),
	('gourmand'),
	('sweet'),
	('resinous'),
	('fruity'),
	('sweet'),
	('floral'),
	('spicy'),
	('spicy'),
	('woody'),
	('woody'),
	('spicy'),
	('oriental'),
	('citrusy'),
	('spicy'),
	('citrusy'),
	('gourmand'),
	('oriental'),
	('oriental'),
	('spicy'),
	('spicy'),
	('floral'),
	('powdery'),
	('oriental'),
	('spicy'),
	('woody'),
	('spicy'),
	('sweet'),
	('sweet');
	


CREATE TABLE IF NOT EXISTS parfumosql (
    "ID" INT PRIMARY KEY,
    "fragrance" TEXT,
    "fraghouse" TEXT,
    "rating" NUMERIC(2, 1),
    "sex" TEXT,
    "sweet" TEXT,
    "floral" TEXT,
    "powdery" TEXT,
    "oriental" TEXT,
    "chypre" TEXT,
    "green" TEXT,
    "gourmand" TEXT,
    "resinous" TEXT,
    "spicy" TEXT,
    "leathery" TEXT,
    "citrusy" TEXT,
    "woody" TEXT,
    "earthy" TEXT,
    "animalic" TEXT,
    "creamy" TEXT,
    "smoky" TEXT,
    "aquatic" TEXT,
    "fougere" TEXT,
    "fresh" TEXT
);
INSERT INTO parfumosql VALUES (1,'Oud (2020)','Aaron Terence Hughes',9,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(2,'Onyx Extreme','Aaron Terence Hughes',9.3,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(3,'Oud  Eau de Parfum','Acqua di Parma',8.4,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(4,'9pm','Afnan Perfumes',8.5,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(5,'Détour Noir','Al Haramain / الحرمين',8.6,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(6,'Sunshine Woman','Amouage',8.2,'Female','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(7,'Memoir Woman (Eau de Parfum)','Amouage',8.4,'Female','no','no','no','yes','no','no','no','no','yes','no','no','no','no','no','no','no','no','no','no'),
	(8,'Dia Woman (Extrait de Parfum)','Amouage',8.8,'Female','no','yes','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(9,'Lyric Woman (Extrait de Parfum)','Amouage',8.8,'Female','no','yes','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(10,'Epic Man','Amouage',8.2,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(11,'Interlude 53','Amouage',8.8,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(12,'Jubilation XXV Man','Amouage',8.5,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(13,'Reflection 45','Amouage',8.8,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(14,'Reflection Man','Amouage',8.7,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(15,'Salam','Anfas',8.7,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(16,'Musk Lave','Areej Le Doré',8.9,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(17,'Atlantic Ambergris II','Areej Le Doré',8.8,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(18,'Triumph of Bacchus (Eau de Parfum)','Argos',8.9,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(19,'Club de Nuit Intense Man Limited Edition','Armaf',8.9,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(20,'Oud Save The King  Eau de Parfum','Atkinsons',8.3,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(21,'Khaltat Night (Eau de Parfum)','Attar Collection',8.6,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(22,'Vent Vert (1947) (Eau de Toilette)','Balmain',8.6,'Female','no','yes','no','no','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(23,'Gris Charnel (Eau de Parfum)','bdk Parfums',8.3,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(24,'Aura Sublime','Bijon',8.6,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(25,'Le Gemme - Kobraa','Bvlgari',8.8,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(26,'CH Men Privé','Carolina Herrera',8.2,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(27,'Tabac Blond (Eau de Parfum)','Caron',8.6,'Female','no','no','no','no','no','no','no','no','yes','yes','no','no','no','no','no','no','no','no','no'),
	(28,'Tabac Blond (1919) (Parfum)','Caron',9.2,'Female','no','no','no','no','no','no','no','no','yes','yes','no','no','no','no','no','no','no','no','no'),
	(29,'Panthère de Cartier (Parfum)','Cartier',8.6,'Female','no','yes','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(30,'Must de Cartier (Parfum)','Cartier',8.9,'Female','no','no','no','yes','no','no','no','no','yes','no','no','no','no','no','no','no','no','no','no'),
	(31,'Santos  Eau de Toilette Concentrée','Cartier',8.7,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(32,'Black Tie','Celine',8.7,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(33,'31 Rue Cambon (Eau de Parfum)','Chanel',8.5,'Female','no','yes','no','no','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(34,'Le Lion de Chanel','Chanel',8.4,'Female','no','no','no','no','no','no','no','yes','no','no','no','no','no','no','no','no','no','no','no'),
	(35,'N°5 Eau Première','Chanel',8.3,'Female','no','yes','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(36,'Coco Mademoiselle (Parfum)','Chanel',8.9,'Female','yes','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(37,'Coco Mademoiselle (Eau de Parfum Intense)','Chanel',8.4,'Female','yes','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(38,'Cuir de Russie (Parfum)','Chanel',9.1,'Female','no','no','no','no','no','no','no','no','yes','yes','no','no','no','no','no','no','no','no','no'),
	(39,'N°19 (Eau de Toilette)','Chanel',8.6,'Female','no','yes','no','no','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(40,'Sycomore (2008) (Eau de Toilette)','Chanel',8.5,'Female','no','no','no','no','no','no','no','no','yes','no','no','yes','no','no','no','no','no','no','no'),
	(41,'N°5 (Eau de Parfum)','Chanel',8.6,'Female','no','yes','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(42,'Coromandel (Eau de Toilette)','Chanel',8.5,'Female','no','no','no','yes','no','no','no','no','no','no','no','yes','no','no','no','no','no','no','no'),
	(43,'Coco (Eau de Parfum)','Chanel',8.6,'Female','no','no','no','yes','no','no','no','no','yes','no','no','no','no','no','no','no','no','no','no'),
	(44,'Coco (Eau de Toilette)','Chanel',8.8,'Female','no','no','no','yes','no','no','no','no','yes','no','no','no','no','no','no','no','no','no','no'),
	(45,'N°19 (Eau de Parfum)','Chanel',8.9,'Female','no','yes','no','no','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(46,'Coco (Parfum)','Chanel',9.2,'Female','no','yes','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(47,'Bois des Îles (Parfum)','Chanel',9.4,'Female','no','yes','no','no','no','no','no','no','no','no','no','yes','no','no','no','no','no','no','no'),
	(48,'Sycomore (2016) (Eau de Parfum)','Chanel',8.5,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(49,'Coromandel (Eau de Parfum)','Chanel',8.7,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(50,'Pour Monsieur  Eau de Toilette','Chanel',8.3,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(51,'Égoïste  Eau de Toilette','Chanel',8.3,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(52,'Bleu de Chanel  Eau de Parfum','Chanel',8.3,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(53,'Allure Homme Sport Eau Extrême','Chanel',8.4,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(54,'Bleu de Chanel Parfum','Chanel',8.4,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(55,'Allure Homme Édition Blanche  Eau de Parfum','Chanel',8.6,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(56,'AddictiveArts - Vision in a Dream Psychedelic','Clive Christian',8.9,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(57,'AddictiveArts - Jump Up and Kiss Me Hedonistic','Clive Christian',8.9,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(58,'Virgin Island Water','Creed',8.3,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(59,'Royal Oud','Creed',8.4,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(60,'Les Royales Exclusives - Sublime Vanille','Creed',8.5,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(61,'Aventus Cologne','Creed',8.3,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(62,'Green Irish Tweed','Creed',8.2,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(63,'Aventus  Eau de Parfum','Creed',8.6,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(64,'Ambre Tabac','Daniel Josier',8.6,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(65,'Miss Dior (1947) (Eau de Toilette)','Dior',8.7,'Female','no','yes','no','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(66,'Miss Dior (Eau de Toilette Originale)','Dior',8.7,'Female','no','yes','no','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(67,'Fève Délicieuse','Dior',8.3,'Female','yes','no','no','no','no','no','yes','no','no','no','no','no','no','no','no','no','no','no','no'),
	(68,'Dior Addict (2002) (Eau de Parfum)','Dior',8.5,'Female','yes','no','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(69,'J''adore L''Or (2017)','Dior',8.8,'Female','yes','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(70,'Dior Addict (2014) (Eau de Parfum)','Dior',8.5,'Female','yes','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(71,'Poison (Eau de Toilette)','Dior',8.7,'Female','no','yes','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(72,'Ambre Nuit','Dior',8.5,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(73,'Dior Homme (2005)','Dior',8.5,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(74,'Dior Homme Intense (2007)','Dior',8.6,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(75,'Eau Sauvage Parfum (2012)','Dior',8.4,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(76,'Eau Sauvage  Eau de Toilette','Dior',8.3,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(77,'Eau Sauvage Parfum (2017)','Dior',8.4,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(78,'Dior Homme Original (2011)  Eau de Toilette','Dior',8.6,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(79,'Dior Homme Parfum','Dior',8.8,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(80,'Dior Homme Intense (2011)','Dior',8.7,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(81,'The One Luminous Night','Dolce & Gabbana',8.7,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(82,'By Man','Dolce & Gabbana',8.8,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(83,'The One for Men  Eau de Parfum','Dolce & Gabbana',8.6,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(84,'Portrait of a Lady','Editions de Parfums Frédéric Malle',8.2,'Female','no','yes','no','no','no','no','no','no','yes','no','no','no','no','no','no','no','no','no','no'),
	(85,'Oud Yusuf (Pure Parfum)','Ensar Oud / Oriscent',9.1,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(86,'EO N°3 (Pure Parfum)','Ensar Oud / Oriscent',9.1,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(87,'Private Collection (Eau de Parfum)','Estēe Lauder',8.4,'Female','no','yes','no','no','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(88,'Theorema (Eau de Parfum)','Fendi',8.6,'Female','no','no','no','yes','no','no','no','no','yes','no','no','no','no','no','no','no','no','no','no'),
	(89,'Oud Noir Intense','Fragrance Du Bois',8.6,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(90,'Armani (Eau de Toilette)','Giorgio Armani',9,'Female','no','yes','no','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(91,'Armani (Parfum)','Giorgio Armani',8.8,'Female','no','yes','no','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(92,'Armani Privé - Rouge Malachite','Giorgio Armani',8.4,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(93,'Armani Privé - Oud Royal','Giorgio Armani',8.5,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(94,'Armani Privé - Cuir Majesté','Giorgio Armani',8.7,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(95,'Armani Privé - Sable Or','Giorgio Armani',8.7,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(96,'Acqua di Giò Profumo  Parfum','Giorgio Armani',8.4,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(97,'Giorgio for Men V.I.P. Special Reserve  Eau de Toilette','Giorgio Beverly Hills',8.9,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(98,'L''Interdit (2021) (Eau de Parfum Rouge)','Givenchy',8.5,'Female','yes','no','no','no','no','no','no','no','yes','no','no','no','no','no','no','no','no','no','no'),
	(99,'Insensé  Eau de Toilette','Givenchy',8.6,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(100,'Gentleman Givenchy  Eau de Parfum','Givenchy',8.3,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(101,'Gentleman Givenchy Réserve Privée','Givenchy',8.6,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(102,'Hasu-no-Hana (Eau de Parfum)','Grossmith',8.8,'Female','no','yes','no','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(103,'Gucci Intense Oud','Gucci',8.5,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(104,'Gucci pour Homme (2003)  Eau de Toilette','Gucci',8.5,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(105,'Envy for Men  Eau de Toilette','Gucci',8.6,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(106,'Shalimar Parfum Initial','Guerlain',8.2,'Female','no','no','yes','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(107,'Parure','Guerlain',8.6,'Female','no','yes','no','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(108,'L''Heure de Nuit','Guerlain',8.4,'Female','no','yes','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(109,'Samsara (Eau de Toilette)','Guerlain',8.4,'Female','no','yes','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(110,'Vol de Nuit (Eau de Toilette)','Guerlain',8.4,'Female','no','no','no','no','no','no','no','no','yes','no','no','yes','no','no','no','no','no','no','no'),
	(111,'Mitsouko (Eau de Toilette)','Guerlain',8.5,'Female','no','no','no','no','yes','no','no','no','yes','no','no','no','no','no','no','no','no','no','no'),
	(112,'Après L''Ondée (Eau de Toilette)','Guerlain',8.4,'Female','no','yes','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(113,'Shalimar (Eau de Parfum)','Guerlain',8.3,'Female','no','no','no','yes','no','no','no','no','yes','no','no','no','no','no','no','no','no','no','no'),
	(114,'Les Élixirs Charnels - Gourmand Coquin','Guerlain',8.4,'Female','yes','no','no','no','no','no','yes','no','no','no','no','no','no','no','no','no','no','no','no'),
	(115,'Mon Guerlain (Eau de Parfum)','Guerlain',8.3,'Female','yes','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(116,'Shalimar Ode à la Vanille - Sur la route de Madagascar','Guerlain',8.6,'Female','no','no','no','yes','no','no','no','no','yes','no','no','no','no','no','no','no','no','no','no'),
	(117,'Chamade (Extrait)','Guerlain',9,'Female','no','yes','no','no','no','no','no','no','yes','no','no','no','no','no','no','no','no','no','no'),
	(118,'Eau de Shalimar','Guerlain',8.5,'Female','no','no','yes','no','no','no','no','no','no','no','yes','no','no','no','no','no','no','no','no'),
	(119,'Shalimar (Eau de Cologne)','Guerlain',8.9,'Female','no','no','yes','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(120,'Guet-Apens','Guerlain',8.8,'Female','no','yes','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(121,'L''Instant Magic (Eau de Parfum)','Guerlain',8.4,'Female','no','yes','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(122,'Mon Précieux Nectar','Guerlain',8.5,'Female','yes','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(123,'Mon Guerlain (Eau de Parfum Intense)','Guerlain',8.6,'Female','yes','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(124,'L''Heure Bleue (Eau de Parfum)','Guerlain',8.5,'Female','no','yes','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(125,'L''Heure Bleue (Eau de Toilette)','Guerlain',8.8,'Female','no','yes','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(126,'Shalimar (Eau de Toilette)','Guerlain',8.7,'Female','no','no','yes','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(127,'Shalimar Ode à la Vanille - Sur la route du Mexique','Guerlain',8.8,'Female','no','no','no','yes','no','no','no','no','yes','no','no','no','no','no','no','no','no','no','no'),
	(128,'Samsara (Extrait)','Guerlain',9.1,'Female','no','yes','no','no','no','no','no','no','no','no','no','yes','no','no','no','no','no','no','no'),
	(129,'Vol de Nuit (Extrait)','Guerlain',9,'Female','no','no','no','no','no','yes','no','no','yes','no','no','no','no','no','no','no','no','no','no'),
	(130,'Shalimar Millésime Tonka','Guerlain',8.9,'Female','no','no','yes','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(131,'Shalimar Millésime Vanilla Planifolia','Guerlain',8.8,'Female','yes','no','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(132,'Shalimar Philtre de Parfum','Guerlain',8.8,'Female','yes','no','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(133,'L''Heure Bleue (Extrait)','Guerlain',9.1,'Female','no','yes','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(134,'Jicky (Extrait)','Guerlain',9.1,'Female','no','no','no','no','no','no','no','no','yes','no','no','no','no','no','no','no','no','no','no'),
	(135,'Shalimar (Extrait)','Guerlain',9.2,'Female','no','no','yes','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(136,'Mitsouko (Extrait)','Guerlain',9.2,'Female','no','no','no','no','yes','no','no','no','yes','no','no','no','no','no','no','no','no','no','no'),
	(137,'Bois d''Arménie','Guerlain',8.5,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(138,'Spiritueuse Double Vanille','Guerlain',8.6,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(139,'Angélique Noire','Guerlain',8.7,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(140,'Tonka Impériale','Guerlain',8.7,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(141,'Cuir Béluga','Guerlain',8.7,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(142,'Héritage  Eau de Parfum','Guerlain',8.5,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(143,'Héritage  Eau de Toilette','Guerlain',8.5,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(144,'Habit Rouge  Eau de Cologne','Guerlain',9,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(145,'L''Instant de Guerlain pour Homme  Eau de Toilette','Guerlain',8.4,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(146,'Derby (1985)  Eau de Toilette','Guerlain',9.2,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(147,'L''Homme Idéal  Eau de Parfum','Guerlain',8.4,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(148,'L''Instant de Guerlain pour Homme  Eau de Parfum','Guerlain',8.5,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(149,'Roi Sans Equipage  Extrait de Parfum','Henry Jacques',9.2,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(150,'Hermessence Ambre Narguilé','Hermès',8.5,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(151,'Terre d''Hermès  Eau de Toilette','Hermès',8.3,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(152,'Terre d''Hermès  Parfum','Hermès',8.5,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(153,'Oud for Greatness','Initio',8.4,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(154,'Side Effect','Initio',8.4,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(155,'Rehab','Initio',8.5,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(156,'La Belle Le Parfum','Jean Paul Gaultier',8.5,'Female','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(157,'Classique Essence de Parfum','Jean Paul Gaultier',8.6,'Female','yes','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(158,'Le Mâle Le Parfum','Jean Paul Gaultier',8.4,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(159,'Jean-Louis Scherrer (Eau de Parfum)','Jean-Louis Scherrer',8.9,'Female','no','no','no','no','yes','yes','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(160,'Man Pure  Eau de Toilette','Jil Sander',8.8,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(161,'Background  Eau de Toilette','Jil Sander',8.6,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(162,'Nuit d''été (Eau de Toilette)','Joop!',8.6,'Female','yes','no','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(163,'KL (Eau de Toilette)','Karl Lagerfeld',8.7,'Female','no','no','no','yes','no','no','no','no','yes','no','no','no','no','no','no','no','no','no','no'),
	(164,'Vanilla | 28','Kayali',8.3,'Female','yes','no','no','no','no','no','yes','no','no','no','no','no','no','no','no','no','no','no','no'),
	(165,'Kenzo Amour','Kenzo',8.2,'Female','yes','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(166,'Angels'' Share','Kilian',8.6,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(167,'Intoxicated','Kilian',8.4,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(168,'La Nuit Trésor à la Folie','Lancôme',8.5,'Female','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(169,'Balahé (Eau de Toilette)','Léonard',8.6,'Female','no','yes','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(170,'Vanille West Indies','Ligne St Barth',8.4,'Female','yes','no','no','no','no','no','yes','no','no','no','no','no','no','no','no','no','no','no','no'),
	(171,'Esencia  Eau de Parfum','Loewe',8.5,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(172,'Afternoon Swim','Louis Vuitton',8.5,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(173,'Ombre Nomade','Louis Vuitton',8.6,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(174,'Imagination','Louis Vuitton',8.8,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(175,'Kismet (2016)','Lubin',8.5,'Female','no','no','yes','no','no','no','no','no','yes','no','no','no','no','no','no','no','no','no','no'),
	(176,'Oud Satin Mood (Eau de Parfum)','Maison Francis Kurkdjian',8.4,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(177,'Baccarat Rouge 540 (Extrait de Parfum)','Maison Francis Kurkdjian',8.6,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(178,'Grand Soir','Maison Francis Kurkdjian',8.6,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(179,'Oud Satin Mood (Extrait de Parfum)','Maison Francis Kurkdjian',8.8,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(180,'masculin Pluriel','Maison Francis Kurkdjian',8.2,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(181,'Lumière Noire Homme','Maison Francis Kurkdjian',8.3,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(182,'Amyris Homme  Extrait de Parfum','Maison Francis Kurkdjian',8.5,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(183,'Ganymede','Marc-Antoine Barrois',8.3,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(184,'Cuirs Nomades - African Leather (Eau de Parfum)','Memo Paris',8.4,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(185,'Club Black','Mercedes-Benz',8.5,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(186,'Missoni Wave','Missoni',8.3,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(187,'Habanita (1988) (Eau de Toilette)','Molinard',8.5,'Female','no','no','no','yes','no','no','no','no','yes','no','no','no','no','no','no','no','no','no','no'),
	(188,'Alien Liqueur de Parfum - Création 2013','Mugler',8.6,'Female','yes','no','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(189,'Alien Essence Absolue','Mugler',8.5,'Female','yes','no','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(190,'A*Men Pure Malt','Mugler',8.3,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(191,'A*Men Pure Havane','Mugler',8.5,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(192,'Dubai - Rimal','Nabeel',8.9,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(193,'Amatys','Nabucco',8.7,'Female','yes','no','no','no','no','no','yes','no','no','no','no','no','no','no','no','no','no','no','no'),
	(194,'Black Afgano (Extrait de Parfum)','Nasomatto',8.3,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(195,'Baraonda (Extrait de Parfum)','Nasomatto',8.6,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(196,'Pardon  Extrait de Parfum','Nasomatto',8.4,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(197,'L''Air du Temps (Parfum)','Nina Ricci',9.3,'Female','no','yes','no','no','no','no','no','no','yes','no','no','no','no','no','no','no','no','no','no'),
	(198,'Wūlóng Chá (Extrait de Parfum)','Nishane',8.3,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(199,'Ani (Extrait de Parfum)','Nishane',8.4,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(200,'Nefs','Nishane',8.9,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(201,'Hacivat','Nishane',8.4,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(202,'Il Capriccio del Maestro','Nobile 1942',9.1,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(203,'2. Nawab of Oudh Intensivo','Ormonde Jayne',9,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(204,'Ormonde Man  Parfum','Ormonde Jayne',8.8,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(205,'Delina (Eau de Parfum)','Parfums de Marly',8.3,'Female','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(206,'Delina Exclusif','Parfums de Marly',8.4,'Female','yes','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(207,'Carlisle','Parfums de Marly',8.5,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(208,'Herod','Parfums de Marly',8.7,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(209,'Pegasus','Parfums de Marly',8.1,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(210,'Oajan','Parfums de Marly',8.6,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(211,'Layton Exclusif','Parfums de Marly',8.5,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(212,'Layton','Parfums de Marly',8.7,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(213,'New York Intense','Parfums de Nicolaï',8.4,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(214,'Chypre Palatin','Parfums MDCI',8.4,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(215,'Emperor Extrait (Extrait)','Parfums Vintage',8.7,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(216,'Portraits - The Tragedy of Lord George','Penhaligon''s',8.4,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(217,'Infusion d''Iris Absolue','Prada',8.5,'Female','no','yes','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(218,'Olfactories - Cargo de Nuit','Prada',8.5,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(219,'Luna Rossa Black','Prada',8.4,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(220,'L''Homme Intense','Prada',8.5,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(221,'L''Homme','Prada',8.5,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(222,'Mriga','Prin',8.9,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(223,'White','Puredistance',8.5,'Female','no','yes','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(224,'Insurrection II Wild','Reyane Tradition',8.3,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(225,'Moustache  Eau de Parfum','Rochas',8.3,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(226,'51 (Eau de Parfum)','Roja Parfums',8.4,'Female','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(227,'51 (Parfum)','Roja Parfums',8.8,'Female','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(228,'Aoud Absolue Précieux','Roja Parfums',9.3,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(229,'Roja','Roja Parfums',8.6,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(230,'Diaghilev (Parfum)','Roja Parfums',8.4,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(231,'A Midsummer Dream','Roja Parfums',8.4,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(232,'Parfum de la Nuit 3','Roja Parfums',8.7,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(233,'Amber Aoud (Parfum)','Roja Parfums',8.6,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(234,'Amber Aoud Absolue Précieux','Roja Parfums',9.1,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(235,'Reckless pour Homme  Parfum','Roja Parfums',8.6,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(236,'Vetiver  Parfum','Roja Parfums',8.5,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(237,'Burlington 1819','Roja Parfums',8.5,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(238,'Madison pour Homme','Roja Parfums',8.9,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(239,'Enigma pour Homme  Eau de Parfum','Roja Parfums',8.5,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(240,'Oligarch  Eau de Parfum','Roja Parfums',8.8,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(241,'Elysium Parfum Cologne  Eau de Parfum','Roja Parfums',8.6,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(242,'Oligarch  Parfum','Roja Parfums',9,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(243,'Enigma pour Homme  Parfum','Roja Parfums',8.8,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(244,'Elysium pour Homme  Parfum','Roja Parfums',9,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(245,'Féminité du Bois (Eau de Parfum)','Shiseido / 資生堂',8.8,'Female','no','no','no','no','no','no','no','no','yes','no','no','yes','no','no','no','no','no','no','no'),
	(246,'Baque','Slumberhouse',8.8,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(247,'Norne (2012)','Slumberhouse',8.4,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(248,'Taklamakan','Stéphane Humbert Lucas',8.3,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(249,'Black Gemstone','Stéphane Humbert Lucas',8.4,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(250,'№ 02 - L''Air du Désert Marocain (Eau de Toilette Intense)','Tauer Perfumes',8.8,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no');
INSERT INTO parfumosql VALUES (251,'Au Coeur du Désert','Tauer Perfumes',8.8,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(252,'Carved Oud (Extrait de Parfum)','Thameen',8.7,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(253,'King of Judea Attar','The Dua Brand / Dua Fragrances',8.9,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(254,'Royal Chariot Attar','The Dua Brand / Dua Fragrances',8.8,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(255,'Casino Elixir 2.0','The Dua Brand / Dua Fragrances',8.6,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(256,'Popped Cherry','The Dua Brand / Dua Fragrances',8.6,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(257,'Naram''s Elixir','The Dua Brand / Dua Fragrances',8.8,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(258,'La Fenice pour Femme','The Merchant Of Venice',8.3,'Female','yes','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(259,'Arabesque','The Merchant Of Venice',8.6,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(260,'Noir pour Femme','Tom Ford',8.5,'Female','yes','no','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(261,'Mandarino di Amalfi (Eau de Parfum)','Tom Ford',8.3,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(262,'Noir de Noir (Eau de Parfum)','Tom Ford',8.3,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(263,'Ombré Leather (2018) (Eau de Parfum)','Tom Ford',8.5,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(264,'Tobacco Vanille (Eau de Parfum)','Tom Ford',8.4,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(265,'Tuscan Leather (Eau de Parfum)','Tom Ford',8.5,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(266,'Lost Cherry (Eau de Parfum)','Tom Ford',8.4,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(267,'Oud Wood (Eau de Parfum)','Tom Ford',8.7,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(268,'Beau de Jour  Eau de Parfum','Tom Ford',8.2,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(269,'Noir Extreme  Eau de Parfum','Tom Ford',8.6,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(270,'Valentino Uomo Intense','Valentino',8.8,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(271,'Valentino Uomo Intense (2016)','Valentino',8.6,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(272,'Collection Extraordinaire - Bois Doré','Van Cleef & Arpels',8.4,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(273,'Collection Extraordinaire - Orchidée Vanille','Van Cleef & Arpels',8.4,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(274,'Spicebomb Extreme','Viktor & Rolf',8.6,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(275,'Gold Collection - II Sahara','Widian / AJ Arabia',8.6,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(276,'Sapphire Collection - London','Widian / AJ Arabia',8.9,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(277,'Casamorati - Dama Bianca (Eau de Parfum)','XerJoff',8.3,'Female','yes','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(278,'Accento','XerJoff',8.3,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(279,'Oud Stars - Fars','XerJoff',8.4,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(280,'Casamorati - Bouquet Ideale (Eau de Parfum)','XerJoff',8.4,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(281,'Oud Stars - Alexandria III','XerJoff',8.6,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(282,'Alexandria II (Pure Attar)','XerJoff',9.6,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(283,'Join The Club - 40 Knots','XerJoff',8.5,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(284,'Oud Stars - Alexandria Orientale','XerJoff',8.8,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(285,'Join The Club - Torino21','XerJoff',8.6,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(286,'Tony Iommi Monkey Special','XerJoff',8.6,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(287,'Shooting Stars - Uden','XerJoff',8.6,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(288,'Casamorati - Lira (Eau de Parfum)','XerJoff',8.6,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(289,'Amber Star','XerJoff',8.8,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(290,'Oud Stars - Alexandria II (Parfum)','XerJoff',8.8,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(291,'XJ 1861 Naxos','XerJoff',8.9,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(292,'Opium (1977) (Eau de Toilette)','Yves Saint Laurent',8.9,'Female','no','no','no','yes','no','no','no','no','yes','no','no','no','no','no','no','no','no','no','no'),
	(293,'Libre (Eau de Parfum Intense)','Yves Saint Laurent',8.3,'Female','yes','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(294,'Manifesto Le Parfum','Yves Saint Laurent',8.6,'Female','yes','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(295,'Manifesto L''Elixir','Yves Saint Laurent',8.6,'Female','yes','no','no','yes','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(296,'Opium (Secret de Parfum)','Yves Saint Laurent',9.2,'Female','no','no','no','yes','no','no','no','no','yes','no','no','no','no','no','no','no','no','no','no'),
	(297,'Le Vestiaire - Tuxedo','Yves Saint Laurent',8.6,'Unisex','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(298,'Opium pour Homme  Eau de Parfum','Yves Saint Laurent',8.6,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(299,'La Nuit de L''Homme Bleu Électrique','Yves Saint Laurent',8.6,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no'),
	(300,'La Nuit de L''Homme  Eau de Toilette','Yves Saint Laurent',8.5,'Male','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no','no');

CREATE TABLE IF NOT EXISTS perfumers (
    "id" INT PRIMARY KEY,
    "perfumer" TEXT
);
INSERT INTO perfumers VALUES (1,'Aaron Terence Hughes'),
	(2,'Aaron Terence Hughes'),
	(3,'Other'),
	(4,'Other'),
	(5,'Other'),
	(6,'Sidonie Lancesseur'),
	(7,'Dorothée Piot'),
	(8,'Jean-Claude Ellena'),
	(9,'Daniel Maurel'),
	(10,'Randa Hammami'),
	(11,'Pierre Negrin'),
	(12,'Bertrand Duchaufour'),
	(13,'Lucas Sieuzac'),
	(14,'Lucas Sieuzac'),
	(15,'Chris Maurice'),
	(16,'Other'),
	(17,'Other'),
	(18,'Other'),
	(19,'Other'),
	(20,'Amandine Clerc-Marie'),
	(21,'Other'),
	(22,'Germaine Cellier'),
	(23,'Mathilde Bijaoui'),
	(24,'Cécile Zarokian'),
	(25,'Jacques Cavallier-Belletrud'),
	(26,'Christophe Raynaud'),
	(27,'Ernest Daltroff'),
	(28,'Ernest Daltroff'),
	(29,'Alberto Morillas'),
	(30,'Jean-Jacques Diener'),
	(31,'Other'),
	(32,'Other'),
	(33,'Jacques Polge'),
	(34,'Olivier Polge'),
	(35,'Jacques Polge'),
	(36,'Jacques Polge'),
	(37,'Olivier Polge'),
	(38,'Ernest Beaux'),
	(39,'Henri Robert'),
	(40,'Jacques Polge'),
	(41,'Jacques Polge'),
	(42,'Jacques Polge'),
	(43,'Jacques Polge'),
	(44,'Jacques Polge'),
	(45,'Henri Robert'),
	(46,'Jacques Polge'),
	(47,'Ernest Beaux'),
	(48,'Jacques Polge'),
	(49,'Jacques Polge'),
	(50,'Henri Robert'),
	(51,'Jacques Polge'),
	(52,'Jacques Polge'),
	(53,'Jacques Polge'),
	(54,'Olivier Polge'),
	(55,'Jacques Polge'),
	(56,'Other'),
	(57,'Other'),
	(58,'Other'),
	(59,'Julien Rasquinet'),
	(60,'Other'),
	(61,'Other'),
	(62,'Pierre Bourdon'),
	(63,'Other'),
	(64,'Daniel Josier'),
	(65,'Paul Vacher'),
	(66,'Edmond Roudnitska'),
	(67,'François Demachy'),
	(68,'Thierry Wasser'),
	(69,'François Demachy'),
	(70,'François Demachy'),
	(71,'Jean Guichard'),
	(72,'François Demachy'),
	(73,'Olivier Polge'),
	(74,'François Demachy'),
	(75,'François Demachy'),
	(76,'Edmond Roudnitska'),
	(77,'François Demachy'),
	(78,'François Demachy'),
	(79,'François Demachy'),
	(80,'François Demachy'),
	(81,'Jean-Christophe Hérault'),
	(82,'Other'),
	(83,'Olivier Polge'),
	(84,'Dominique Ropion'),
	(85,'Other'),
	(86,'Other'),
	(87,'Vincent Marcello'),
	(88,'Christine Nagel'),
	(89,'François Merle-Baudoin'),
	(90,'Ron Winnegrade'),
	(91,'Ron Winnegrade'),
	(92,'Pascal Gaurin'),
	(93,'Evelyne Boulanger'),
	(94,'Other'),
	(95,'Other'),
	(96,'Alberto Morillas'),
	(97,'Other'),
	(98,'Dominique Ropion'),
	(99,'Daniel Molière'),
	(100,'Olivier Cresp'),
	(101,'Nathalie Lorson'),
	(102,'Other'),
	(103,'Other'),
	(104,'Michel Almairac'),
	(105,'Daniela Andrier'),
	(106,'Thierry Wasser'),
	(107,'Jean-Paul Guerlain'),
	(108,'Thierry Wasser'),
	(109,'Jean-Paul Guerlain'),
	(110,'Jacques Guerlain'),
	(111,'Jacques Guerlain'),
	(112,'Jacques Guerlain'),
	(113,'Jacques Guerlain'),
	(114,'Christine Nagel'),
	(115,'Thierry Wasser'),
	(116,'Thierry Wasser'),
	(117,'Jean-Paul Guerlain'),
	(118,'Jean-Paul Guerlain'),
	(119,'Jacques Guerlain'),
	(120,'Mathilde Laurent'),
	(121,'Randa Hammami'),
	(122,'Randa Hammami'),
	(123,'Thierry Wasser'),
	(124,'Jacques Guerlain'),
	(125,'Jacques Guerlain'),
	(126,'Jacques Guerlain'),
	(127,'Thierry Wasser'),
	(128,'Jean-Paul Guerlain'),
	(129,'Jacques Guerlain'),
	(130,'Thierry Wasser'),
	(131,'Thierry Wasser'),
	(132,'Thierry Wasser'),
	(133,'Jacques Guerlain'),
	(134,'Aimé Guerlain'),
	(135,'Jacques Guerlain'),
	(136,'Jacques Guerlain'),
	(137,'Annick Ménardo'),
	(138,'Jean-Paul Guerlain'),
	(139,'Daniela Andrier'),
	(140,'Thierry Wasser'),
	(141,'Olivier Polge'),
	(142,'Jean-Paul Guerlain'),
	(143,'Jean-Paul Guerlain'),
	(144,'Jean-Paul Guerlain'),
	(145,'Béatrice Piquet'),
	(146,'Jean-Paul Guerlain'),
	(147,'Thierry Wasser'),
	(148,'Béatrice Piquet'),
	(149,'Other'),
	(150,'Jean-Claude Ellena'),
	(151,'Jean-Claude Ellena'),
	(152,'Jean-Claude Ellena'),
	(153,'Other'),
	(154,'Other'),
	(155,'Other'),
	(156,'Quentin Bisch'),
	(157,'Daphné Bugey'),
	(158,'Nathalie Gracia-Cetto'),
	(159,'Other'),
	(160,'Jacques Artarit'),
	(161,'Jean-François Latty'),
	(162,'Other'),
	(163,'Roger Pellégrino'),
	(164,'Gabriela Chelariu'),
	(165,'Daphné Bugey'),
	(166,'Benoist Lapouza'),
	(167,'Calice Becker'),
	(168,'Christophe Raynaud'),
	(169,'Daniel Molière'),
	(170,'Other'),
	(171,'Other'),
	(172,'Jacques Cavallier-Belletrud'),
	(173,'Jacques Cavallier-Belletrud'),
	(174,'Jacques Cavallier-Belletrud'),
	(175,'Thomas Fontaine'),
	(176,'Francis Kurkdjian'),
	(177,'Francis Kurkdjian'),
	(178,'Francis Kurkdjian'),
	(179,'Francis Kurkdjian'),
	(180,'Francis Kurkdjian'),
	(181,'Francis Kurkdjian'),
	(182,'Francis Kurkdjian'),
	(183,'Quentin Bisch'),
	(184,'Aliénor Massenet'),
	(185,'Other'),
	(186,'Christophe Raynaud'),
	(187,'Roure Bertrand'),
	(188,'Other'),
	(189,'Dominique Ropion'),
	(190,'Jacques Huclier'),
	(191,'Jacques Huclier'),
	(192,'Asghar Adam Ali'),
	(193,'Other'),
	(194,'Alessandro Gualtieri'),
	(195,'Alessandro Gualtieri'),
	(196,'Alessandro Gualtieri'),
	(197,'Francis Fabron'),
	(198,'Jorge Lee'),
	(199,'Cécile Zarokian'),
	(200,'Chris Maurice'),
	(201,'Jorge Lee'),
	(202,'Michelle Moellhausen'),
	(203,'Geza Schön'),
	(204,'Geza Schön'),
	(205,'Quentin Bisch'),
	(206,'Quentin Bisch'),
	(207,'Quentin Bisch'),
	(208,'Olivier Pescheux'),
	(209,'Hamid Merati-Kashani'),
	(210,'Shyamala Maisondieu'),
	(211,'Hamid Merati-Kashani'),
	(212,'Hamid Merati-Kashani'),
	(213,'Patricia de Nicolaï'),
	(214,'Bertrand Duchaufour'),
	(215,'Other'),
	(216,'Alberto Morillas'),
	(217,'Daniela Andrier'),
	(218,'Daniela Andrier'),
	(219,'Daniela Andrier'),
	(220,'Daniela Andrier'),
	(221,'Daniela Andrier'),
	(222,'Prin Lomros'),
	(223,'Antoine Lie'),
	(224,'Other'),
	(225,'Nathalie Gracia-Cetto'),
	(226,'Roja Dove'),
	(227,'Roja Dove'),
	(228,'Roja Dove'),
	(229,'Roja Dove'),
	(230,'Roja Dove'),
	(231,'Roja Dove'),
	(232,'Roja Dove'),
	(233,'Roja Dove'),
	(234,'Roja Dove'),
	(235,'Roja Dove'),
	(236,'Roja Dove'),
	(237,'Roja Dove'),
	(238,'Roja Dove'),
	(239,'Roja Dove'),
	(240,'Roja Dove'),
	(241,'Roja Dove'),
	(242,'Roja Dove'),
	(243,'Roja Dove'),
	(244,'Roja Dove'),
	(245,'Pierre Bourdon'),
	(246,'Josh Lobb'),
	(247,'Josh Lobb'),
	(248,'Stéphane Humbert Lucas'),
	(249,'Stéphane Humbert Lucas'),
	(250,'Andy Tauer');
INSERT INTO perfumers VALUES (251,'Andy Tauer'),
	(252,'Alexandre Illan'),
	(253,'Other'),
	(254,'Other'),
	(255,'Other'),
	(256,'Other'),
	(257,'Other'),
	(258,'Other'),
	(259,'Other'),
	(260,'Sonia Constant'),
	(261,'Calice Becker'),
	(262,'Harry Frémont'),
	(263,'Sonia Constant'),
	(264,'Olivier Gillotin'),
	(265,'Harry Frémont'),
	(266,'Louise Turner'),
	(267,'Richard Herpin'),
	(268,'Antoine Maisondieu'),
	(269,'Sonia Constant'),
	(270,'Other'),
	(271,'Sophie Labbé'),
	(272,'Fabrice Pellegrin'),
	(273,'Randa Hammami'),
	(274,'Other'),
	(275,'Other'),
	(276,'Jordi Fernández'),
	(277,'Other'),
	(278,'Other'),
	(279,'Other'),
	(280,'Jacques Flori'),
	(281,'Other'),
	(282,'Other'),
	(283,'Other'),
	(284,'Other'),
	(285,'Other'),
	(286,'Other'),
	(287,'Other'),
	(288,'Other'),
	(289,'Other'),
	(290,'Other'),
	(291,'Other'),
	(292,'Jean-Louis Sieuzac'),
	(293,'Anne Flipo'),
	(294,'Anne Flipo'),
	(295,'Other'),
	(296,'Jean-Louis Sieuzac'),
	(297,'Juliette Karagueuzoglou'),
	(298,'Jacques Cavallier-Belletrud'),
	(299,'Dominique Ropion'),
	(300,'Anne Flipo');
	
/* Viewing top 5 rows from each table to validate */

SELECT * FROM parfumoaccords
LIMIT 5;

SELECT * FROM parfumosql 
LIMIT 5;

SELECT * FROM perfumers
LIMIT 5;

/* Working correctly */

/* Finding number of accords and most common accords */

SELECT COUNT(DISTINCT(accord1))
FROM parfumoaccords;

SELECT accord1, COUNT(accord1)
FROM parfumoaccords
GROUP BY accord1
ORDER BY COUNT(accord1) DESC;

/* 20 total accords exist. Top 5: Spicy(120), Sweet(108), Floral(67), Woody(64), Oriental(55) */

/*Next, find top 5 most popular brands according to number on the list */

SELECT fraghouse AS brand, COUNT(fraghouse)
FROM parfumosql 
GROUP BY fraghouse
ORDER BY COUNT(fraghouse) DESC
LIMIT 5;

/* Results: Guerlain(43), Chanel(23), Roja(19), Dior(16), XerJoff(15) */

/* Next, find brands with highest average rating (3 fragrance minimum) */

SELECT fraghouse AS brand, ROUND(AVG(rating), 2)
FROM parfumosql 
GROUP BY fraghouse
HAVING COUNT(fraghouse) >= 3
ORDER BY AVG(rating) DESC;

/* 
Results: Dua(8.74), Cartier(8.73), Roja(8.71), D & G(8.70), Guerlain(8.67)
Note that because this is a list of top 300, all ratings will be relatively high in the scale. 
*/

/* Next, finding most popular perfumers. We will exclude 'Other' in this case */

SELECT perfumer, COUNT(perfumer)
FROM perfumers
WHERE perfumer != 'Other'
GROUP BY perfumer
ORDER BY COUNT(perfumer) DESC
LIMIT 5;

/* Results: Roja Dove(19), Jacques Polge(15), Jacques Guerlain(12), Thierry Wasser(12) J.P Guerlain(10) */

/* Next, a simple inner join to see both the fragrance, house, and pefumer */

SELECT fragrance, fraghouse AS brand, perfumers.perfumer
FROM parfumosql
INNER JOIN perfumers
ON parfumosql."ID" = perfumers."id";






